<?php

/**
 * @file
 * Provides synonyms integration with Commerce.
 */

/**
 * Implements hook_synonyms_behavior_implementation_info().
 */
function synonyms_commerce_synonyms_behavior_implementation_info($behavior) {
  switch ($behavior) {
    case 'select':
    case 'autocomplete':
      return array(
        'commerce_product_reference' => 'CommerceProductReferenceSynonymsBehavior',
      );
      break;

    case 'search':
      return array(
        'commerce_product_reference' => 'SearchCommerceProductReferenceSynonymsBehavior',
      );
      break;
  }
  return array();
}
